### ISSUE TITLE
Remove or deprecate non-actually-working extensions ?

### ISSUE THREAD

**Issue by greystate** [leekelleher/umbraco-7-exslt-redux#1]
If I recall correctly, some of the extensions (like `sets:distict()` for instance) doesn't actually work — would it be nice to just remove them or can we deprecate them somehow? (Best option would of course be to actually fix them :-)

**Comment by leekelleher** [comment]
:+1: I'll try to fix them.

I had looked at fixing them in the past, but don't recall what roadblocks I hit. :vertical_traffic_light:

If I can't fix them, I can mark them as `Obsolete`, (in C#), but that won't change how these are used in XSLT directly.

Alternatively we could return a custom node-set containing an error message? But again that changes the expected behaviour. :tired_face:

**Comment by greystate** [comment]
Let me guess: `XMLDocumentFragment` woes? (_We hatesss them..._ :-)

My thinking is something like this: No-one (or less than 0.01%) are using the botched extensions, yet they're documented as if they work. So if we did some auto-generation of docs (from the pseudo-XML included with every extension), we could also make sure to add a note to the ones that doesn't actually work, thus making the documentation useful... ?

**Comment by leekelleher** [comment]
@greystate I'm closing this one off, (I'm finally doing some housekeeping on my GitHub repos).

I doubt I'll ever get around to looking at this; along with that demand for EXSLT is virtually non-existent within the Umbraco community.

**Comment by greystate** [comment]
No worries :)
